# CMIP5, LOCA: Calculate A and B for Non-Precipitation

To use the AR, lag-1 approach for the non-precipitation parameters, two matrices are required to generate the solution for current values from lag-1 values and error terms.

In [1]:
%matplotlib inline

In [2]:
import os
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
IN_DIR1 = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\D' \
          r'ata\JNotes\Processed\CMIP5\OtherWeather_1981-2010'
IN_DIR2 = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\D' \
          r'ata\JNotes\Processed\CMIP5\OtherWeather_2011-2040'
IN_DIR3 = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\D' \
          r'ata\JNotes\Processed\CMIP5\OtherWeather_2041-2070'
IN_DIR4 = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\D' \
          r'ata\JNotes\Processed\CMIP5\OtherWeather_2071-2100'

In [4]:
IN1_R0 = r'OWeath_LOCA_Z_M0_1981-2010.pickle'
IN1_R1 = r'OWeath_LOCA_Z_M1_1981-2010.pickle'
IN2_R0 = r'OWeath_LOCA_Z_M0_2011-2040.pickle'
IN2_R1 = r'OWeath_LOCA_Z_M1_2011-2040.pickle'
IN3_R0 = r'OWeath_LOCA_Z_M0_2041-2070.pickle'
IN3_R1 = r'OWeath_LOCA_Z_M1_2041-2070.pickle'
IN4_R0 = r'OWeath_LOCA_Z_M0_2071-2100.pickle'
IN4_R1 = r'OWeath_LOCA_Z_M1_2071-2100.pickle'

In [5]:
OUT_DIR = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\Data\JN' \
          r'otes\Processed\PRISM\Other_Weather'

In [6]:
InFiler = os.path.normpath( os.path.join( IN_DIR1, IN1_R0 ) )
rho0DF1 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR1, IN1_R1 ) )
rho1DF1 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR2, IN2_R0 ) )
rho0DF2 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR2, IN2_R1 ) )
rho1DF2 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR3, IN3_R0 ) )
rho0DF3 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR3, IN3_R1 ) )
rho1DF3 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR4, IN4_R0 ) )
rho0DF4 = pd.read_pickle( InFiler )
InFiler = os.path.normpath( os.path.join( IN_DIR4, IN4_R1 ) )
rho1DF4 = pd.read_pickle( InFiler )

Check the correlation coefficients should be 1.0 to 0.0

In [7]:
display( HTML( rho0DF1.to_html() ))

In [8]:
display( HTML( rho0DF2.to_html() ))

In [9]:
display( HTML( rho0DF3.to_html() ))

In [10]:
display( HTML( rho0DF4.to_html() ))

Check the lag-1 cross correlation coefficients, expecting -1 to 1

In [11]:
display( HTML( rho1DF1.to_html() ))

In [12]:
display( HTML( rho1DF2.to_html() ))

In [13]:
display( HTML( rho1DF3.to_html() ))

In [14]:
display( HTML( rho1DF4.to_html() ))

## Matrix Inversion Solutions

\begin{equation*}
    M_{0} = \begin{bmatrix}
                1               & \rho_{0}(1,2)    & \rho_{0}(1,3) \\
                \rho_{0}(2,1)   &      1           & \rho_{0}(2,3) \\
                \rho_{0}(3,1)   & \rho_{0}(3,2)    & 1             \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    M_{1} = \begin{bmatrix}
                \rho_{1}(1,1)   & \rho_{1}(1,2)    & \rho_{1}(1,3) \\
                \rho_{1}(2,1)   & \rho_{1}(2,2)    & \rho_{1}(2,3) \\
                \rho_{1}(3,1)   & \rho_{1}(3,2)    & \rho_{1}(3,3) \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    A M_{0} = M_{1}
\end{equation*}

\begin{equation*}
    A = M_{0}^{-1} M_{1}
\end{equation*}

\begin{equation*}
    B = M_{0} - A M_{1}^{T}
\end{equation*}

### Data Period: 1981-2010

In [15]:
M0_0 = rho0DF1.to_numpy()
M1_0 = rho1DF1.to_numpy()

In [16]:
A0 = np.matmul( M1_0, np.linalg.inv( M0_0 ) )

In [17]:
A0

array([[0.61759594, 0.14081637],
       [0.08925376, 0.62306957]])

In [18]:
B0 = np.linalg.cholesky( M0_0 - np.matmul( np.matmul( M1_0, np.linalg.inv( M0_0 ) ), M1_0.T ) )

In [19]:
B0

array([[0.70545863, 0.        ],
       [0.29388859, 0.67291597]])

### Project Period 1: 2011-2040

In [20]:
M0_1 = rho0DF2.to_numpy()
M1_1 = rho1DF2.to_numpy()

In [21]:
A1 = np.matmul( M1_1, np.linalg.inv( M0_1 ) )

In [22]:
A1

array([[0.6232303 , 0.1474739 ],
       [0.08809282, 0.63728267]])

In [23]:
B1 = np.linalg.cholesky( M0_1 - np.matmul( np.matmul( M1_1, np.linalg.inv( M0_1 ) ), M1_1.T ) )

In [24]:
B1

array([[0.69258303, 0.        ],
       [0.29542339, 0.65692135]])

### Project Period 2: 2041-2070

In [25]:
M0_2 = rho0DF3.to_numpy()
M1_2 = rho1DF3.to_numpy()

In [26]:
A2 = np.matmul( M1_2, np.linalg.inv( M0_2 ) )

In [27]:
A2

array([[0.62576301, 0.15244654],
       [0.0887346 , 0.64952574]])

In [28]:
B2 = np.linalg.cholesky( M0_2 - np.matmul( np.matmul( M1_2, np.linalg.inv( M0_2 ) ), M1_2.T ) )

In [29]:
B2

array([[0.68365113, 0.        ],
       [0.29779058, 0.64061725]])

### Project Period 3: 2041-2070

In [30]:
M0_3 = rho0DF4.to_numpy()
M1_3 = rho1DF4.to_numpy()

In [31]:
A3 = np.matmul( M1_3, np.linalg.inv( M0_3 ) )

In [32]:
A3

array([[0.6333683 , 0.16722986],
       [0.09390023, 0.6749836 ]])

In [33]:
B3 = np.linalg.cholesky( M0_3 - np.matmul( np.matmul( M1_3, np.linalg.inv( M0_3 ) ), M1_3.T ) )

In [34]:
B3

array([[0.65746134, 0.        ],
       [0.29203635, 0.6060881 ]])